# Manual steps
# sudo apt update
#sudo apt install openjdk-11-jdk -y
#sudo useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat
#cd /tmp/
#wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.10/bin/apache-tomcat-10.0.10.tar.gz
name: installing and updating tomcat on ubuntu
become: yes
hosts: all
tasks:
  - name: this file is used only ubuntu machine
    ansible.builtin.fail:
      msg: "this playbook for ubuntu "
    when: ansible_facts[os_family]!= 'Debian' && ansible_facts[os_family]!= 'RedHat'
  - name: insatlling java 11 on ubuntu
    ansible.builtin.apt:
      name: "{{java_package}}"
      update_cache: yes
      state: present
    when: ansible_facts[os_family]= 'Debian'
  - name: installing java 11 on RedHat
    ansible.builtin.dnf:
      name: "{{java_package}}"
      update_cache: yes
      state: present
  - name: creating a tomcat group
    ansible.builtin.group:
      name: "{{group}}"
      state: present
  - name: Creating a user
    ansible.builtin.user:
      create_home: yes
      name: "{{user}}"
      home: "{{home_directory}}"
      group: "{{group}}"
      shell: "{{user_sheel}}"
      system: true
      state: present
  - ansible.builtin.debug:
        msg: "user {{ user }} has been created"
  - name: tomcat downloaded
    ansible.builtin.unarchive:
      src: "{{ tomcat_url }}"
      dest: "{{ home_directory }}"
      owner: "{{ user }}"
      remote_src: yes
  - ansible.builtin.debug:
        msg: "tomcat is downloaded and extracted to {{ home_dir  }}"
  - name: find all the shell files
    find:
      paths: "/opt/tomcat/apache-tomcat-10.0.10/bin"
      patterns: '*.sh'
    register: shell_files
  - name: change permissions to execute
    file:
      path: "{{ item.path }}"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: "755"
    loop: "{{ shell_files.files }}"