---
name: installing and updating packages 
hosts: all
become: yes
tasks:
  - name: installing apache on ubuntu
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present
    when: ansible_facts['os_family'] == "Debian"
  - name: installing apache on RedHat
    ansible.builtin.dnf:
      name: httpd
      update_cache: yes
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  - name: enble and start service
    ansible.builtin.systemd_service:
      name: "{{package_name}}"
      enbled: yes
      state: started
---     