---
name: installing and updating packages 
hosts: all
become: yes
tasks:
  - name: Install httpd on fail
    ansible.builtin.fail:
      msg: "this playbook for ubuntu and Redhat"
    when: ansible_facts[os_family]!= 'RedHat' and ansible_facts[os_family]!= 'Debian'
  - name: installing apache
    package:
      name: "{{package_name}}"
      update_cache: yes
      state: present
  - name: enble and start service
    ansible.builtin.systemd_service:
      name: "{{package_name}}"
      enbled: yes
      state: started
---     