---
name: installing and updating packages 
hosts: all
become: yes
tasks:
  - name: installing apache on ubuntu
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present
    when: ansible_facts['os_family'] == "Debian"
  - name: enble and start apche on ubuntu
    ansible.builtin.systemd_service:
      name: apache2
      enbled: yes
      state: started
    when: ansible_facts['os_family'] == "Debian"
  - name: installing apache on RedHat
    ansible.builtin.dnf:
      name: httpd
      update_cache: yes
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  - name: enble and start apche on RedHat
    ansible.builtin.systemd_service:
      name: httpd
      enbled: yes
      state: started
    when: ansible_facts['os_family'] == "RedHat"
---     